const categories = {
  'illustration': {
    title: 'Illustration',
    color: 'cyan',
    images: [
      'Out-in-space.jpg',
      'Birds.jpg',
      'quake-B.jpg',
      'Realia.jpg',
      'Emoji.jpg',
      'Natural.jpg',
      'Aerial.jpg',
      'Out-in-space.jpg',
      'cutaway.jpg',
      'Birds.jpg',
      'Pavlov.jpg',
      'quake-B.jpg',
      'Cambrian.jpg',
      'Realia.jpg',
      'renewable.jpg',
      'Emoji.jpg',
      'Step-step.jpg',
      'Natural.jpg',
      'beneath-sea.jpg'
    ],
  },
  'infographics': {
    title: 'Infographics',
    color: 'magenta',
    images: [
      'Aerial.jpg',
      'cutaway.jpg',
      'Pavlov.jpg',
      'Cambrian.jpg',
      'renewable.jpg',
      'Step-step.jpg',
      'beneath-sea.jpg',
      'Out-in-space.jpg',
      'cutaway.jpg',
      'Birds.jpg',
      'Pavlov.jpg',
      'Cambrian.jpg',
      'Emoji.jpg',
      'Natural.jpg',
    ],
  },
  'design': {
    title: 'Design',
    color: 'yellow',
    images: [
      'cutaway.jpg',
      'Birds.jpg',
      'Pavlov.jpg',
      'quake-B.jpg',
      'Cambrian.jpg',
      'Realia.jpg',
      'renewable.jpg',
      'Emoji.jpg',
      'Step-step.jpg',
      'Natural.jpg',
      'beneath-sea.jpg'
    ],
  },
  'maps': {
    title: 'Maps',
    color: 'green',
    images: [
      'Aerial.jpg',
      'Out-in-space.jpg',
      'cutaway.jpg',
      'Birds.jpg',
      'Pavlov.jpg',
      'quake-B.jpg',
      'Cambrian.jpg',
      'Realia.jpg',
      'renewable.jpg',
      'Emoji.jpg',
      'Step-step.jpg',
      'Natural.jpg',
      'beneath-sea.jpg',
      'Aerial.jpg',
      'Out-in-space.jpg',
      'cutaway.jpg',
      'Birds.jpg',
      'Pavlov.jpg',
      'quake-B.jpg',
      'Cambrian.jpg',
      'Realia.jpg',
      'renewable.jpg',
      'Emoji.jpg',
      'Step-step.jpg',
      'Natural.jpg',
      'beneath-sea.jpg'
    ],
  },
  'tech-art': {
    title: 'Tech Art',
    color: 'red',
    images: [
      'Aerial.jpg',
      'Out-in-space.jpg',
      'cutaway.jpg',
      'Birds.jpg',
      'Pavlov.jpg',
      'quake-B.jpg',
      'Cambrian.jpg',
      'Realia.jpg',
      'renewable.jpg',
      'Emoji.jpg',
      'Step-step.jpg',
      'Natural.jpg',
      'beneath-sea.jpg',
      'Aerial.jpg',
      'Out-in-space.jpg',
      'cutaway.jpg',
      'Birds.jpg',
      'Pavlov.jpg',
      'quake-B.jpg',
      'Cambrian.jpg',
      'Realia.jpg',
      'renewable.jpg',
      'Emoji.jpg',
      'Step-step.jpg',
      'Natural.jpg',
      'beneath-sea.jpg'
    ],
  }
};
export default categories;
